### ISSUE TITLE
Working with a "restricted" sheet?

### ISSUE THREAD

**Issue by dahanj95** [SteveWinward/GoogleSheetsWrapper#11]
Hi, is it possible to make crud operations on a "restricted" sheet? A sheet that is not open for R/W for anyone, just for the owner. Thanks.

**Comment by SteveWinward** [comment]
@dahanj95 you do not need to make a Google sheet publicly accessible to use this api. You can grant only yourself and your developer service account access to the spreadsheet. 

Take a look at the authentication steps in the readme for this library to see how to set it up. 

https://github.com/SteveWinward/GoogleSheetsWrapper#authentication

When I run tests for this library I use a private Google sheet to do the testing. 

Hope this helps!

**Comment by dahanj95** [comment]
> You can grant only yourself and your developer service account access to the spreadsheet.

Can you tell me how I can grant my developer service account access to the restricted spreadsheet?

**Comment by SteveWinward** [comment]
First you need to create a Google developer account and then you can create a service account. Instructions for the service account are linked below,

https://cloud.google.com/docs/authentication/production#create_service_account

Once you have the service account created you can add its email address to have access to your Google Sheet you are working with. The code for this library will then run as the service account to read and write to the Google Sheet you want to work with. 

Hope this helps.

**Comment by dahanj95** [comment]
I don't understand! Can you please guide me step by step what to do on the cloud console in order to get it working with restricted sheets???

**Comment by SteveWinward** [comment]
Here’s a really good write up how to create the service account, download the json credential file and then add the service account to the Google sheet. 

https://robocorp.com/docs/development-guide/google-sheets/interacting-with-google-sheets#create-a-google-service-account

**Comment by dahanj95** [comment]
You're really trying hard not to answer my question, why can't you just tell me which settings in the service account I have to enable in order to grant access to restricted sheets? I have the .json file and email, I have created a service account based on my email, but it won't run on a restricted sheet!

**Comment by SteveWinward** [comment]
Hey @dahanj95 I’m sorry there is a disconnect here.  

It sounds like you already have your service account created. The final step is in your Google Sheet you need to share it with the identity of the Google service account. Below is a screenshot of that step. Have you done this yet?


![](https://robocorp.com/docs/d97b167f9f58bb5c8ca32ebcac3a453d/spreadsheet-add-user-as-editor.png)

**Comment by dahanj95** [comment]
Thank you!, that's what I needed! :D

**Comment by SteveWinward** [comment]
Excellent. Is it working for you now?

**Comment by dahanj95** [comment]
No, I am getting 'Error:"invalid_grant", Description:"Not a valid email or user ID.". What the hell is this?

**Comment by SteveWinward** [comment]
@dahanj95 I know you are frustrated trying to get this setup. I would really recommend to take a look through this article and double check you have done all the steps of both sections. 

https://robocorp.com/docs/development-guide/google-sheets/interacting-with-google-sheets#create-a-google-service-account

https://robocorp.com/docs/development-guide/google-sheets/interacting-with-google-sheets#create-a-new-google-sheet-and-add-the-service-account-as-an-editor-to-it

Note that the last step shows you how to get the specific url for the Google sheet you want to access via code. 

Hope this helps.

**Comment by dahanj95** [comment]
Just tell me how to resolve the last error and that's it, please.

**Comment by SteveWinward** [comment]
@dahanj95 glad to hear you got it working. I hope you find the library useful. Best of luck.
