### ISSUE TITLE
Fetching rows that contain specific column data?

### ISSUE THREAD

**Issue by dahanj95** [SteveWinward/GoogleSheetsWrapper#12]
Hi, is it possible to query rows that contain specific column data? for example, if i have a "date" column and it can either contain "n/a" or "12/06/2022" can i fetch only those that contain "n/a" directly without having to filter using linq afterwards? Thanks.

**Comment by SteveWinward** [comment]
@dahanj95 that’s a great question. Unfortunately I have not found a way with the Google Sheets API to filter the data by a specific condition. The only way I have achieved this is looping over the data afterwards like using LINQ. 

Here’s a stackoverflow post that someone asks a similar question as well,

https://stackoverflow.com/questions/62789700/google-sheets-api-read-values-by-filter
