### ISSUE TITLE
An item with the same key has already been added.

### ISSUE THREAD

**Issue by dahanj95** [SteveWinward/GoogleSheetsWrapper#13]
This is my code when I try to create a repo for 2 different sheets in the same document id.

```
    public SheetWatchdog(int seconds, string json, string sheet_id, string service_email)
    {
        var usersHelper = new SheetHelper<SheetRecord>(sheet_id, service_email, "Sheet1");
        var reloadHelper = new SheetHelper<ReloadRecord>(sheet_id, service_email, "Sheet2");

        _usersSheet = new SheetRepository(usersHelper);
        _reloadSheet = new ReloadRepository(reloadHelper); // this line throws exception

        usersHelper.Init(json);
        reloadHelper.Init(json);

        Schedule(this).NonReentrant().ToRunNow().AndEvery(seconds).Seconds();
    }
```

How can I use the same credentials for the same sheet with different tabs? Thanks!

**Comment by SteveWinward** [comment]
This should work. I’ve done this before for other projects having multiple tabs. 

Do you mind sharing the full stack trace error message?  It’s hard to tell what could be going on without that. 

Also, if you were to comment out the usersHelper and usersSheet lines and only create the reloadSheet does it work?  I’m wondering if there is something with how you are mapping that record type.

**Comment by dahanj95** [comment]
![image](https://user-images.githubusercontent.com/21217427/173902226-79e8b8c5-dfc2-4125-b9a0-efab769acceb.png)

Here's an image of the call stack.

> Also, if you were to comment out the usersHelper and usersSheet lines and only create the reloadSheet does it work?

Yes.

**Comment by SteveWinward** [comment]
I’ll be honest I’m not sure what is causing this issue you are seeing. Do you mind showing what your ReloadRecord and SheetRecord classes look like?

**Comment by SteveWinward** [comment]
After walking through the stack trace I think the issue is that in your ReloadRecord class you have a SheetField attribute that reuses the same ColumnID. I don’t think it has to do with the fact that you have two different SheetHelper objects.

**Comment by SteveWinward** [comment]
Excellent!
