### ISSUE TITLE
I want to update rows, not append them

### ISSUE THREAD

**Issue by darma-exe** [SteveWinward/GoogleSheetsWrapper#18]
Thank you for your great library.

Does a way to update row content already exist on the library?

I envision a use case where a particular range is kept up to date using `SheetHelper::ClearRange()` and the update method.

**Comment by SteveWinward** [comment]
@darma-exe,

In the ````SheetHelper```` class you can use the ````BatchUpdate(List<BatchUpdateRequestObject> updates)```` method.  You pass it a collection of updates and you can update multiple cells with that method.  Is this what you are looking for?

Also if you are using the strongly typed option, the ````BaseRespository```` and ````BaseRecord```` classes let you do this,

````csharp
firstRecord.PriceAmount = 99.99;
repository.SaveField(firstRecord, (r) => r.PriceAmount);
````

**Comment by darma-exe** [comment]
Thanks for the support, I was able to write using the SheetHelper::BatchUpdate() method.

If I don't want to overwrite an existing style (e.g. color) of a cell, do I need to get the existing style beforehand.

**Comment by SteveWinward** [comment]
Check out version 1.0.41 on nuget now.

**Comment by SteveWinward** [comment]
One last update!  In 1.0.42 you can now specify a custom field mask.  If you use "*", that will update every property of the cells in the request.  The method defaults to only updating the userEnteredValue.  But you can override that now.

**Comment by SteveWinward** [comment]
I added some documentation to the readme file to explain the different field masks you can use here,

https://github.com/SteveWinward/GoogleSheetsWrapper#batch-updates
