### ISSUE TITLE
just a small thank you...

### ISSUE THREAD

**Issue by schittli** [SteveWinward/GoogleSheetsWrapper#20]
Hello
**thanks a lot for sharing your great work!,**
for a non-profit project, I tried to get up and running with the Google Sheets API myself and stumbled a dozen times, unfortunately, the API feels like assembler programming and it lacks smart features for basic functions.

Then, I found by chance GoogleSheetsWrapper 😊.

You really put a lot of great work into the project, it's quite fun to work with because you thought of 'minor' details and even wrote a useful doc.

Thanks a lot & all the best!
kind regards,
Thomas

**Comment by SteveWinward** [comment]
Thank you so much for the kind words. I had the exact same experience about a year ago. I was also working with a non profit to automate Google Sheets and I struggled to use the low level Google Sheets API. 

Let me know if there’s any suggestions you have for the library. You can also make a pull request to make additions to the library too!
