### ISSUE TITLE
How to update a record?

### ISSUE THREAD

**Issue by HughMacdonald** [SteveWinward/GoogleSheetsWrapper#26]
I've been building some code around this library, and one thing I've not figured out is how best to update a record. I've had to create my own batch using `record.ConvertToCellData()`, but it would be great to have `UpdateRecord()` and `UpdateRecords()` to wrap this.

**Comment by SteveWinward** [comment]
@HughMacdonald, have you seen the strongly typed examples on the readme page?

https://github.com/SteveWinward/GoogleSheetsWrapper#core-operations-strongly-typed

You can call the BaseRepository class SaveField / SaveFields methods to avoid making a ConvertToCellData method. This does require you to model strongly typed objects first though.
