### ISSUE TITLE
Nullable build warnings

### ISSUE THREAD

**Issue by SteveWinward** [SteveWinward/GoogleSheetsWrapper#27]
@HughMacdonald can you take a look at the new build warnings showing up after the update you made for nullable return types?

You can see the build output below, 

https://github.com/SteveWinward/GoogleSheetsWrapper/actions/runs/6597726518

An example of the build warning is below,

“The annotation for nullable reference types should only be used in code within a '#nullable' annotations context.”

**Comment by HughMacdonald** [comment]
This is not something that I've ever come across in my own code before

**Comment by HughMacdonald** [comment]
I won't be able to take a proper look until next week at some point

**Comment by SteveWinward** [comment]
No worries.  It’s only a build warning but would be nice to get them removed for future builds. Thank you @HughMacdonald

**Comment by SteveWinward** [comment]
Just updated the class to no longer emit the build warnings for nullable references.
