### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by ancich** [SteveWinward/GoogleSheetsWrapper#3]
I have looked everywhere but I cannot seem to find any code (or at least clear code in C#) that shows how to add a blank row (for a new record) between EXISTING records  (i.e. "insert row").

**Comment by ancich** [comment]
That would be FANTASTIC.   I have seen that exact page that you pointed me to, but I have zero idea how to implement that in my c# program. I currently have stuff working, like adding a row at the end, reading values and changing values, but it is the INSERT that I really, really need.  I'd be happy even with brute force "no helper" code at this point.  As soon as anything starts including things like POST and REST, my eyes glaze just glaze over.  I am currently using "using Google.Apis.Sheets.v4" but it's documentation is cryptic.   It sounds like I have to do a "batch update"
POST https://sheets.googleapis.com/v4/spreadsheets/spreadsheetId:batchUpdate
and somehow magically give it these field and/or data
{
  "requests": [
    {
      "moveDimension": {
        "source": {
          "sheetId": sheetId,
          "dimension": "ROWS",
          "startIndex": 4,
          "endIndex": 10
        },
        "destinationIndex": 19
      }
    },
  ],
}

... so confused.

PS: If  you need other features to add:  return number of rows (or columns) in the sheet,  get the name of the tabs,  any easy way to select a specific sheet if the worksheet has several tabs,  ability to export sheet to csv,  ability to import sheet FROM csv, and many, many more

**Comment by SteveWinward** [comment]
## New Insert Blank Row Method

I just added a new method to the SheetHelper class to allow you to insert a blank row at any given row number.  This example below will insert a new blank row at row id 2.

```csharp
// Create a SheetHelper class for the default first tab
var sheetHelper = new SheetHelper(
    settings.GoogleSpreadsheetId,
    settings.GoogleServiceAccountName,
    "");

// Initialize the SheetHelper
sheetHelper.Init(settings.JsonCredential);

// insert a new blank row at row 2
helper.InsertBlankRow(2);
```

## Export Methods

With regards to exporting data from Google Sheets, I have two helper methods for that which are documented below,

https://github.com/SteveWinward/GoogleSheetsWrapper#export-google-sheet-to-csv

https://github.com/SteveWinward/GoogleSheetsWrapper#export-google-sheet-to-excel-file

## Tab Operations

To get the name of the tabs in a Google Spreadsheet, you can do this,

```csharp
// Create a SheetHelper class for the default first tab
var sheetHelper = new SheetHelper(
    settings.GoogleSpreadsheetId,
    settings.GoogleServiceAccountName,
    "");

// Initialize the SheetHelper
sheetHelper.Init(settings.JsonCredential);

// Get all tab names in the spreadsheet
var tabs = sheetHelper.GetAllTabNames();

// loop over all tabs
foreach(var tab in tabs)
{
    // update the tab name with the SheetHelper class
    sheetHelper.UpdateTabName(tab);

    // Create the range to be the 1st row to all data rows
    // this also includes the 1st to 8th columns in the range
    var range = new SheetRange(tab, 1, 1, 8);
    var rows = sheetHelper.GetRows(range);
}

```

Hope this helps!

**Comment by SteveWinward** [comment]
No worries.  This GoogleSheetsWrapper library I created is packaged and published to nuget.org.  So you need to make sure that you have imported the published Nuget package for this library.  You can go here to find the latest version that includes the new insert blank row method.

https://www.nuget.org/packages/GoogleSheetsWrapper/

Optionally, if you just want to see the C# code that inserts a new blank row, you can see it here in the source code for the library,

https://github.com/SteveWinward/GoogleSheetsWrapper/blob/main/src/GoogleSheetsWrapper/BaseSheetHelper.cs#L147

Hope this helps.

**Comment by ancich** [comment]
OMG... This reminds me of online dating : I was so hopeful, but disappointed.

It compiled, and ran up to the  line sheetHelper.Init("core-329217-b87fcb9f5b36.json");
where it gives some "unexpected character error"

System.InvalidOperationException






HResult=0x80131509






Message=Error deserializing JSON credential data.






Source=Google.Apis.Auth






StackTrace:






at Google.Apis.Auth.OAuth2.DefaultCredentialProvider.CreateDefaultCredentialFromJson(String json)






at Google.Apis.Auth.OAuth2.GoogleCredential.FromJson(String json)






at GoogleSheetsWrapper.BaseSheetHelper.Init(String jsonCredentials)






at _2013B_Updater007.Form1..ctor() in C:\Users\Ancich\Documents\_blog_2013b\!Project2013B_Updater\2013B_Updater007\2013B_Updater007\Form1.cs:line 87






at _2013B_Updater007.Program.Main() in C:\Users\Ancich\Documents\_blog_2013b\!Project2013B_Updater\2013B_Updater007\2013B_Updater007\Program.cs:line 20














This exception was originally thrown at this call stack:






[External Code]














Inner Exception 1:






JsonReaderException: Unexpected character encountered while parsing value: c. Path '', line 0, position 0.







MY CODE...
    public partial class Form1 : Form
    {

    static readonly string[] Scopes = { SheetsService.Scope.Spreadsheets };
    static readonly string ApplicationName = "2013core";
    static readonly string SpreadsheetId = "1f6MrL1G6tdnkxUEK1q-5c2I2Sv79AH5Jz9pOzocmJlI";
    static readonly string sheet = "Sheet1";
    static SheetsService service;

        public Form1()
        {
            InitializeComponent();

            GoogleCredential credential;
            using (var stream = new FileStream("core-329217-b87fcb9f5b36.json", FileMode.Open, FileAccess.Read))
            {
                credential = GoogleCredential.FromStream(stream)
                    .CreateScoped(Scopes);
            }

            // Create Google Sheets API service.
            service = new SheetsService(new BaseClientService.Initializer()
            {
                HttpClientInitializer = credential,
                ApplicationName = ApplicationName,
            });

            ReadEntries();   // reads and displays google sheet's data in Visual Studio's Output window.

            // ================== GoogleSheetsWrapper
            // sheetID,  serviceaccountEMAIL , Sheetname

            var sheetHelper = new SheetHelper("1f6MrL1G6tdnkxUEK1q-5c2I2Sv79AH5Jz9pOzocmJlI", ***@***.***", "Sheet1");

            sheetHelper.Init("core-329217-b87fcb9f5b36.json");

            // insert a new blank row at row 2
            sheetHelper.InsertBlankRow(2);



☹



Warmest regards,
Johnny Ancich
www.PastExpiry.com<http://www.PastExpiry.com>
https://project2013b.blogspot.com<https://project2013b.blogspot.com/2021/10/welcome.html>





________________________________

**Comment by SteveWinward** [comment]
You need to pass the actual json text of the file you have downloaded. Right now you are passing the name of the json file instead.

**Comment by ancich** [comment]
Oh god... another rabbit hole.  I think my brain just melted
How?    Literally open it as if it were a text file or do I have to delve into deserializing mumbo jumbo and the rabbit hole that will become.





Warmest regards,
Johnny Ancich
www.PastExpiry.com<http://www.PastExpiry.com>
https://project2013b.blogspot.com<https://project2013b.blogspot.com/2021/10/welcome.html>





________________________________

**Comment by ancich** [comment]
OMG! it worked!



Warmest regards,
Johnny Ancich
www.PastExpiry.com<http://www.PastExpiry.com>
https://project2013b.blogspot.com<https://project2013b.blogspot.com/2021/10/welcome.html>





________________________________

**Comment by SteveWinward** [comment]
Excellent. Glad it’s working for you.

**Comment by ancich** [comment]
Hi,

    I might have found a bug when I was mucking around trying some different things.

    in the Append a CSV to Google Sheets feature... if I change the headerline indicator to false, I get an error.


    appender.AppendCsv(
        stream, // The CSV FileStrem
        false, // true indicating to include the header row
        1000);

Basically it is treating my headerless csv file as if the first row of data

was a header, so it kinda freaks out when it sees what it sees as two headers

with the same name (e.g. TBD)

Extensive error details below....





CsvHelper.ReaderException
  HResult=0x80131500
  Message=An unexpected error occurred.
IReader state:
   ColumnCount: 0
   CurrentIndex: 4
   HeaderRecord:
["TRANSFERRED!","Now in main database!","TBD","B*-02-DC","TBD","F2","F16","1","B* 05777576"," ","DC","2021.10.21","M>CT","Prefers to buy"," "," ","Stratford","CT","USA"," "," ","5777576","Michelle ***@***.***"]
IParser state:
   ByteCount: 0
   CharCount: 378
   Row: 2
   RawRow: 2
   Count: 25
   RawRecord:
TRANSFERRED!,Now in main database!,TBD,B*-01-FW,TBD,H2,FWH107,86,B* 00098724," ",FW,2021.10.17,GF>VA,Undecided," "," ",Richmond,VA,USA," "," ***@***.***


  Source=CsvHelper
  StackTrace:
   at CsvHelper.CsvReader.<GetRecords>d__87`1.MoveNext()
   at System.Linq.Enumerable.SelectEnumerableIterator`2.ToList()
   at GoogleSheetsWrapper.SheetAppender.AppendCsv(Stream stream, Boolean includeHeaders, Int32 batchWaitTime)
   at _2013B_Updater007.Form1.QUEUE_CSV_TO_QUEUE_Gsheet() in C:\Users\Ancich\Documents\_blog_2013b\!Project2013B_Updater\2013B_Updater007\2013B_Updater007\Form1.cs:line 2119
   at _2013B_Updater007.Form1.button14_Click(Object sender, EventArgs e) in C:\Users\Ancich\Documents\_blog_2013b\!Project2013B_Updater\2013B_Updater007\2013B_Updater007\Form1.cs:line 2169
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)

  This exception was originally thrown at this call stack:
    [External Code]

Inner Exception 1:
ArgumentException: An element with the same key 'TBD' already exists in the ExpandoObject. (Parameter 'key')



Warmest regards,
Johnny Ancich
www.PastExpiry.com<http://www.PastExpiry.com>
https://project2013b.blogspot.com<https://project2013b.blogspot.com/2021/10/welcome.html>





________________________________

**Comment by SteveWinward** [comment]
Got it.  I think I just reproduced this and pushed a commit just now that should fix that.  Look for the nuget package version 1.0.27 which will include the update.

https://github.com/SteveWinward/GoogleSheetsWrapper/commit/99e0b263e44bc94a105e29917c6378b229af84aa

**Comment by ancich** [comment]
Hi Steve,

    I have been using your wrapper for several months now with no issues.  Anytime there is an issue it is always with the user entering bad data a field in my google form (which dumps to a google sheet) namely stuff like commas.   Is there a way to read the google sheet and dump it to a TAB delimitted csv file, or do I need to find a way to do that upstream on the google form itself?

Regards,
Johnny



Warmest regards,
Johnny Ancich
www.PastExpiry.com<http://www.PastExpiry.com>
https://project2013b.blogspot.com<https://project2013b.blogspot.com/2021/10/welcome.html>





________________________________

**Comment by SteveWinward** [comment]
Hey Johnny,

If you run this code below, do you get an error when exporting to a CSV file?

````csharp
var exporter = new SheetExporter(
    settings.GoogleSpreadsheetId, 
    settings.GoogleServiceAccountName, 
    settings.GoogleMainSheetName);

exporter.Init(settings.JsonCredential);

var filepath = @"C:\Output\output.csv";

using (var stream = new FileStream(filepath, FileMode.Create))
{
    // Query the range A1:G (ie 1st column, 1st row, 8th column and last row in the sheet)
    var range = new SheetRange("TAB_NAME", 1, 1, 8);
    exporter.ExportAsCsv(range, stream);
}

````

**Comment by SteveWinward** [comment]
Understood.  I made a new release of the nuget package.  Download version 1.0.31 from nuget.org.

https://www.nuget.org/packages/GoogleSheetsWrapper/

Once you get the new package, you can use the following new method signature to specify a custom delimiter when you export to CSV,

````csharp
var exporter = new SheetExporter(
    settings.GoogleSpreadsheetId, 
    settings.GoogleServiceAccountName, 
    settings.GoogleMainSheetName);

exporter.Init(settings.JsonCredential);

var filepath = @"C:\Output\output.csv";

using (var stream = new FileStream(filepath, FileMode.Create))
{
    // Query the range A1:G (ie 1st column, 1st row, 8th column and last row in the sheet)
    var range = new SheetRange("TAB_NAME", 1, 1, 8);
    // This tells the file to be "tab" delimited, but you can use any custom delimiter here that you would like
    exporter.ExportAsCsv(range, stream, "\t");
}

`````

**Comment by ancich** [comment]
Hi Steve,

    Cannot believe it was close to 3 years ago you gave me a lot of help with the use of your google sheets helper!  You probably don't remember,  but our back and forth resulted in you adding some more features like dumping a google sheet's data to a CSV file.

    Now I need more help 🙁    I have been using your wrapper for close to 3 years and has been instrumental in making my website successful.  I want to try a new thing where I upload a csv file to a specific tab in an existing google sheet but instead of appending, I would like to be able to just over-write whatever is on the destination sheet named 'DATA".    I know how to delete rows and then append my csv data, but the problem I am running into is that I have formulas on another sheet that references various cells on my 'DATA' sheet, and the formulas end up all displaying #REF!    I am hoping that just overwriting the existing data keeps my formulas on the other sheet tab unharmed.   I suspect your batch command might work, but I am clueless when it comes to 'encapsulated helper classes'....

I hope my issue makes sense.

Warmest regards,
Johnny Ancich
https://project2013b.blogspot.com<https://project2013b.blogspot.com/2021/10/welcome.html>






________________________________
