### ISSUE TITLE
Changing Row or Column properties on a SheetRange is allowed, but doesn't change A1Notation or R1C1Notation

### ISSUE THREAD

**Issue by HughMacdonald** [SteveWinward/GoogleSheetsWrapper#30]
If I've got a SheetRange that was created with a specific TabName, StartColumn, StartRow, etc, it's possible to later change these values, but changing them doesn't cause A1Notation or R1C1Notation to be updated to reflect.

My suggestion would be to have a private method called something like `UpdateNotations()` which can be called at the end of the constructor once the properties are set, and then updating the setters on the public set properties to call this method after setting those properties.

**Comment by SteveWinward** [comment]
@HughMacdonald, That's a good suggestion.  

Do you mind sharing a snippet of the code where you are manipulating SheetRange properties and expect the A1Notation / R1C1Notation to update?  Just want to make sure if we update this, it will help you with your specific use case.

**Comment by HughMacdonald** [comment]
Will do. There may be a better way of doing what I’m currently doing, but whether that’s the case or not, I don’t think that the class should be able to get into a state where the internals don’t make sense.

**Comment by SteveWinward** [comment]
Understood. Your point is completely valid. Let me see if I can refactor the code so that the A1Notation and R1C1Notation generate on the fly so that if you do modify the public set methods for any properties the notations are accurate.

**Comment by HughMacdonald** [comment]
Yeah - that sounds like a good approach. Either re-generate each time they’re required, cache them and invalidate when another property changes, or set them when another property changes.

**Comment by SteveWinward** [comment]
@HughMacdonald 

Just released an updated nuget, version 2.0.3.  Do you mind testing this out to see if this resolves your issue?  The commit details are below,

https://github.com/SteveWinward/GoogleSheetsWrapper/commit/f3ccd59b03a01c40930ef58450f2b831ce99fc89

**Comment by HughMacdonald** [comment]
You could possibly tidy it up and get rid of `Initialized` by setting the private fields in the constructors before calling the method to set the Notations. The constructor that takes a string would just set the private fields and then set the notations and wouldn't need to set Initialized

**Comment by SteveWinward** [comment]
@HughMacdonald. That’s a really good point to set the private fields directly in the constructor to avoid the need for the IsInitialized property. I’ll make an update later for that one.
