### ISSUE TITLE
SheetHelper.GetRows() null return type not handled in BaseRepository. GetAllRecords()

### ISSUE THREAD

**Issue by oozkaya** [SteveWinward/GoogleSheetsWrapper#34]
Hello ! 👋

**Describe the bug**

When using the `GetAllRecords()` method in the `BaseRepository`, if there is no data in the sheet, `GetAllRecords()` will throw a `NullReferenceException`.

**To Reproduce**

Just try to read an empty sheet.

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at GoogleSheetsWrapper.BaseRepository`1.GetAllRecords()
```

**Additional context**

In my use case, I need to fetch my specific row in order to update it or create if not exist. So I need to get all rows and then filter to get my row. But this will throw a null exception as my sheet can be empty (with some headers).

Indeed `GetAllRecords()` is fetching rows with `this.SheetHelper.GetRows(this.SheetDataRange);` which has the return type of `IList<IList<object>>?`, and this nullable is not handled after in the method.

Linked to the issue #24 and PR #25.

Thank you ! 🙂

**Comment by SteveWinward** [comment]
Thanks for reporting this. 

So to reproduce this. You sometimes have a sheet with only header names, but no rows of data in the sheet after the headers?

Also are you using the strongly typed approach here to make a class that represents the sheet data?

**Comment by SteveWinward** [comment]
@oozkaya I was able to reproduce the issue.  I just released a new version (2.0.7).  Do you mind testing the latest nuget package version and verifying this solves your issue?

**Comment by oozkaya** [comment]
Hello Steve ! Sorry for the late answer, and yes I can confirm it solved my issue, thank you ! 🙂

**Comment by SteveWinward** [comment]
@oozkaya , thank you so much for following up.  Glad to hear it solved your issue!
