### ISSUE TITLE
Row offset

### ISSUE THREAD

**Issue by rohan-gaitonde** [SteveWinward/GoogleSheetsWrapper#36]
The SheetField attribute has a ColumnID param to indicate which column corresponds to which property and allows offsetting of columns.

How about offsetting rows? In my scenario, there are 3 blank rows and the headers (and data) actually starts the 4th row onwards. How would I configure this setting in my repository object, so that the data range is configured correctly? By default it starts at the first row.

**Comment by SteveWinward** [comment]
@rohan-gaitonde I haven’t added a row offset capability between the the header and the first row of data. 

Have you tried calling the GetAllRecords method already?  Does it error out?  My first thought was if it doesn’t error out you can skip the first few records. You could also try to make the property nullable which may let you avoid an error getting thrown.

**Comment by SteveWinward** [comment]
@rohan-gaitonde .  I just added a new BaseRepositoryConfiguration class that you can use to specify a row offset for the data table.  This was released in nuget version 2.0.9.  Get the latest version and let me know if this works for you!  Sample snippet below,

````csharp
var repoConfig = new BaseRepositoryConfiguration()
     {
           // Does the table have a header row?
           HasHeaderRow = true,
           // Are there any blank rows before the header row starts?
           HeaderRowOffset = 0,
           // Are there any blank rows before the first row in the data table starts?                
           DataTableRowOffset = 3,
     };

var respository = new SampleRepository(sheetHelper, repoConfig);                

var records = respository.GetAllRecords();
````

**Comment by rohan-gaitonde** [comment]
> @rohan-gaitonde I haven’t added a row offset capability between the the header and the first row of data.
> 
> Have you tried calling the GetAllRecords method already? Does it error out? My first thought was if it doesn’t error out you can skip the first few records. You could also try to make the property nullable which may let you avoid an error getting thrown.

@SteveWinward thanks for the prompt reply. 
I didn't mean row offset between header row and the first data row. I mean row offset for the entire range, including the header). Like this:

![image](https://github.com/SteveWinward/GoogleSheetsWrapper/assets/25236256/5565d744-f806-4e99-8f3f-0ebeb8491989)

Sorry, I should have made that clear.

Regarding GetAllRows, I get System Format Exception:
System.FormatException : Input string was not in a correct format.

This is because its trying to parse the header as a data row.

> @rohan-gaitonde . I just added a new BaseRepositoryConfiguration class that you can use to specify a row offset for the data   > table. This was released in nuget version 2.0.9. Get the latest version and let me know if this works for you! Sample snippet below,

I'll try it and let you know. Thanks.

**Comment by SteveWinward** [comment]
@rohan-gaitonde.  Get the latest nuget version (2.0.9) and try this below.  You can now specify a header row offset which should match the scenario you sent above.  Let me know if this works!

````csharp
var repoConfig = new BaseRepositoryConfiguration()
     {
           // Does the table have a header row?
           HasHeaderRow = true,
           // Are there any blank rows before the header row starts?
           HeaderRowOffset = 2,
           // Are there any blank rows before the first row in the data table starts?                
           DataTableRowOffset = 0,
     };

var respository = new SampleRepository(sheetHelper, repoConfig);                

var records = respository.GetAllRecords();
````

**Comment by rohan-gaitonde** [comment]
@SteveWinward it works well!. Thanks very much!

**Comment by SteveWinward** [comment]
@rohan-gaitonde glad to hear its working for you now!
