### ISSUE TITLE
System.NullReferenceException on AddRecords

### ISSUE THREAD

**Issue by LeoJHarris** [SteveWinward/GoogleSheetsWrapper#38]
Hi @SteveWinward fantastic library, working like a charm for the most part but we ran into an issue on the AddRecords, I have sheet with rows and I am trying to copy over to another sheet, the sheet to copy to only has the header and no existing records currently. When I call the something like this

```csharp
return sheetProfileRepository.AddRecords(sheetProfileRecords);
```

We are getting a NullReferenceException, I also check with this sheetProfileRepository.ValidateSchema() on the sheet I am copying from and works fine. 

Everything looks good on the data to copy over but throwing exception when it comes to calling on the `AddRecords`. I inspected the class which is `SheetProfileRecord : BaseRecord` that I copy and I dont see any null values, only a few empty strings and empty dates.

**Comment by SteveWinward** [comment]
@LeoJHarris are you able to share a screenshot of what your spreadsheet looks like you are trying to copy into?  Can you also share some of the exception details / stack trace?

**Comment by LeoJHarris** [comment]
![image](https://github.com/SteveWinward/GoogleSheetsWrapper/assets/5468757/e66d4f1c-bf5f-4049-800a-4b4aa2054b66)

![image](https://github.com/SteveWinward/GoogleSheetsWrapper/assets/5468757/dca8b6e9-270a-49f6-a35e-2ed0010a4646)

System.NullReferenceException
  HResult=0x80004003
  Message=Object reference not set to an instance of an object.
  Source=GoogleSheetsWrapper
  StackTrace:
   at GoogleSheetsWrapper.SheetHelper`1.AppendRows(IList`1 records)
   at GoogleSheetsWrapper.BaseRepository`1.AddRecords(IList`1 records)
   at SampleApp.Services.GoogleSheetsService.AddRecords(IList`1 sheetProfileRecords) in #############\Services\GoogleSheetsService.cs:line 125

**Comment by LeoJHarris** [comment]
I've stepped into your code and it looks like the `RowData` was null 

```csharp
RowData item = new RowData
			{
				Values = (from b in record.ConvertToCellData(base.TabName)
					select b.Data).ToList()
			};
```
![image](https://github.com/SteveWinward/GoogleSheetsWrapper/assets/5468757/8d69c986-ed81-4bd0-8764-d8c5f5edcdd2)

**Comment by LeoJHarris** [comment]
Finally the spread sheet we pull from looks like this:

![image](https://github.com/SteveWinward/GoogleSheetsWrapper/assets/5468757/71708639-4681-43a2-99f5-b79cea8229be)

And we have setup the `Class` that inherits from `BaseRecord` with properties like this:

```csharp
    [SheetField(
    DisplayName = "Date Of Birth",
        ColumnID = 19,
        FieldType = SheetFieldType.DateTime, NumberFormatPattern = "dd-MM-yyyy")]
    public DateTime DateOfBirth { get; set; }
```
```csharp
    [SheetField(
             DisplayName = "I declare that the information I have given is true and correct",
           ColumnID = 55,
             FieldType = SheetFieldType.String)]
    public string DeclarationOfInformation { get; set; }
```

We currently use the library to read and update existing spread sheet records without issue.

**Comment by SteveWinward** [comment]
Ok. I’ve not run into this before. It may take some time for me to really investigate this. 

My only recommendation in the short term is to try and create a very simple BaseRecord / BaseRepository for the new spreadsheet. Map a single column to a single property. See if you can get that to save. Slowly build it out to the more complicated object you need to save. That’s usually the approach I take when I build these.

**Comment by LeoJHarris** [comment]
> Ok. I’ve not run into this before. It may take some time for me to really investigate this. 
> 
> My only recommendation in the short term is to try and create a very simple BaseRecord / BaseRepository for the new spreadsheet. Map a single column to a single property. See if you can get that to save. Slowly build it out to the more complicated object you need to save. That’s usually the approach I take when I build these. 
> 
> 

Hi @SteveWinward, Thanks for the suggestion, I'll give that a go.

Do you know, however, if the new spreadsheet to copy to already had existing rows that might work better?

**Comment by SteveWinward** [comment]
@LeoJHarris under the covers the code calls the Google Sheets API AppendRow method which simply adds a new row to the end of the table and this works even if the spreadsheet is empty.  I'm not sure why for your use case you are getting the null reference exception.

**Comment by SteveWinward** [comment]
@LeoJHarris I was able to reproduce a null exception in the stack trace.  I believe what is going on is some of the records you are passing are actuall null records,

````csharp
return sheetProfileRepository.AddRecords(sheetProfileRecords);
````

I updated the code and pushing a new Nuget version 2.0.10 which will fix this.

**Comment by LeoJHarris** [comment]
@SteveWinward I have checked but there are no null values, I also tried to add a single item having commented out all but one column property and still got an exception:

![image](https://github.com/SteveWinward/GoogleSheetsWrapper/assets/5468757/ef67471f-4880-41eb-a7a6-da2b79db28e2)

**Comment by LeoJHarris** [comment]
The `base.Service` seems to be null this time:

![image](https://github.com/SteveWinward/GoogleSheetsWrapper/assets/5468757/ee16126b-300a-4a38-bd1b-0089dbb93451)

**Comment by LeoJHarris** [comment]
Seems sheet Id is null on he above screen but I did set this previously

```csharp
public BatchUpdateSpreadsheetResponse AddRecords(IList<SheetProfileRecord> sheetProfileRecords)
    {
        SheetProfileRepository sheetProfileRepository = new(_sheetStagingSuccessfulHelper);
        return sheetProfileRepository.AddRecords(sheetProfileRecords);
    }
```

when I init it here:

```csharp
_sheetStagingSuccessfulHelper = new(_appSettings?.GoogleSheetsID, "googlesheetsapireader@########iam.gserviceaccount.com", "Staging Successful");
```

**Comment by SteveWinward** [comment]
Got it. So in addition to calling the constructor method of SheetHelper. You then need to call the Init() method. This will initiate the Service class. See the main readme file for this repo to see examples of that.

**Comment by LeoJHarris** [comment]
@SteveWinward thanks for that its now working on inserting records, forgot I need to call the `init` per sheet helper so thanks for letting me know, the last question I had was is there a way to copy over the cell formats when it copies row data?

Copied like this:

![image](https://github.com/SteveWinward/GoogleSheetsWrapper/assets/5468757/658afe28-8f6f-4ec6-baa2-7287492c4b72)

Would be good to copy formatting like this:

![image](https://github.com/SteveWinward/GoogleSheetsWrapper/assets/5468757/40c64eb4-edba-4378-bcb4-aa8f16743207)

**Comment by SteveWinward** [comment]
The library supports updating formatting but there isn’t anything today in this library to let you “clone” formatting. If you can apply the formatting to your sheet ahead of time when you write new records it should preserve the formatting for you. 

Always room for a community addition for cloning formatting 😀

**Comment by LeoJHarris** [comment]
> Always room for a community addition for cloning formatting 😀

Hi @SteveWinward I would be happy to be assist in that, I did look at the source code briefly and the get records only appears to include values as they're formatted in the Google Sheets UI so might need to change to also get the `CellData` which would contain all properties for a given cell.

> The library supports updating formatting but there isn’t anything today in this library to let you “clone” formatting. If you can apply the formatting to your sheet ahead of time when you write new records it should preserve the formatting for you.

That would be ideal to get a solution quickly, are you referring to the [batch updates](https://github.com/SteveWinward/GoogleSheetsWrapper?tab=readme-ov-file#batch-updates) and the call the `AddRecord`
