### ISSUE TITLE
SheetExporter giving null error (parameter Element Value cannot be null)

### ISSUE THREAD

**Issue by rlatourio** [SteveWinward/GoogleSheetsWrapper#40]
I've been using this code for a year and it has been working well. In the last few weeks, though, it has started throwing an error:

System.ArgumentNullException: 'Value cannot be null. (Parameter 'element')'

The code is below. The sheet exists, the range is good. These same values worked a couple of months ago. Now they don't. The error comes from the exporter.ExportAsCsv call. 

var sheetHelper = new SheetHelper(documentId, serviceAccount, "Schedule");
sheetHelper.Init(jsonCredsContent);

var exporter = new SheetExporter(sheetHelper);

using (var sched = new FileStream(filepath, FileMode.Create))
{
    var range = new SheetRange("Schedule", 1, 1, 4, 18);
    exporter.ExportAsCsv(range, sched);
}

Am I missing something?

**Comment by SteveWinward** [comment]
That's odd.  Have you been using the same Nuget version of this package?  I'm wondering if you updated it, maybe that's when something changed?  

Are you able to share a more detailed stack trace of the full error stack?

**Comment by rlatourio** [comment]
The stack trace isn't very informative, but here it is:

System.ArgumentNullException
  HResult=0x80004003
  Message=Value cannot be null. (Parameter 'element')
  Source=System.Private.CoreLib
  StackTrace:
   at System.Attribute.GetCustomAttributes(MemberInfo element, Boolean inherit)
   at CsvHelper.Configuration.CsvConfiguration.ApplyAttributes(Type type)
   at CsvHelper.Configuration.CsvConfiguration..ctor(CultureInfo cultureInfo, Type attributesType)
   at GoogleSheetsWrapper.SheetExporter.ExportAsCsv(SheetRange range, Stream stream, String delimiter)
   at Patch_Automation.SheetsUtils.GetRHELPatchDates() in C:\Users\xxx\projects\patch-automation\SheetsUtils.cs:line 42
   at Patch_Automation.PatchAutomation.Main(String[] args) in C:\Users\xxx\projects\patch-automation\PatchAutomation.cs:line 80

**Comment by SteveWinward** [comment]
@rlatourio I just did a test using the latest nuget version to test the export to csv function.  I'm not seeing an error.  

Looking at the stack trace, it appears that where your code is throwing an error is initializing a CsvConfiguration object which is from a separate nuget package I used to help write a csv file.  

I'm curious, if you run just this snipped of code to create a new CsvConfiguration object, does that fail too for you?

````csharp
var config = new CsvConfiguration(CultureInfo.InvariantCulture)
            {
                Delimiter = ",",
            };

````

**Comment by SteveWinward** [comment]
@rlatourio , I added a new ExportCsv method signature.  An example is added to the main readme, but here's how you can use it if you find out you need to set the CultureInfo to another value,

````csharp
// OPTION 2: Create your own CsvConfiguration object with full control on Culture and delimiter
using (var stream = new FileStream(filepath, FileMode.Create))
{
    // Query the range A1:G (ie 1st column, 1st row, 8th column and last row in the sheet)
    var range = new SheetRange("TAB_NAME", 1, 1, 8);

    // This gives you full control on the CSV file CultureInfo and Delimiter value
    var csvConfig = new CsvConfiguration(CultureInfo.CurrentCulture)
    {
        Delimiter = ",",
    };

    // Export with the customer CsvConfiguration value
    exporter.ExportAsCsv(range, stream, csvConfig);
}
````

**Comment by rlatourio** [comment]
Thank you! The changes and the addition of CsvConfiguration work great.

**Comment by SteveWinward** [comment]
Excellent!

If you find other functions in this library you think would benefit from exposing the CultureInfo property please let me know.  I built this in my free time and haven't tested every edge case of all the different CultureInfo scnearios out there.
